### ISSUE TITLE
security holding package

### ISSUE THREAD

**Issue by DanielRuf** [varunon9/amp4email#1]
Hi,

it seems you have accidentally added `fs` but this is not a package on npmjs, `fs` is an internal NodeJS module.

https://github.com/varunon9/amp4email/blob/master/package.json#L27

See https://nodejs.org/api/fs.html

**Comment by varunon9** [comment]
Thanks @DanielRuf for pointing this out. My bad

**Comment by varunon9** [comment]
Fixed
