### ISSUE TITLE
yarn start command not working

### ISSUE THREAD

**Issue by bhaskartalla** [varunon9/amp4email#4]
The following command gives an  "error Command failed with exit code 127." Could you please help on how to resolve the issue. Thank you

**Comment by varunon9** [comment]
Please attach screenshot of cmd/terminal.

**Comment by bhaskartalla** [comment]
<img width="972" alt="Screenshot 2020-02-25 at 3 31 39 PM" src="https://user-images.githubusercontent.com/12645587/75236918-842e2c80-57e4-11ea-91db-8ad4323437bf.png">

this is what I see after running the yarn start cmd.
